EXP:
  EXP_NAME: UperNetAux-sn6-optical-newnrom-complete
  SAVE_DIR: # default : exp/{EXP_NAME}
  DDP: true
MODEL:
  MODEL_NAME: UperNetAux
  NETWORK_NAME: BEiTAdapterUperNetAux
  IN_CHANNELS: 4
  NUM_CLASSES: 1
  PRETRAINED_PATH: '/home/yh.sakong/github/Satellite/pretrained/beit_large_patch16_224_pt22k_ft22k_4channels.pth'
  RESUME_PATH:  
  LOAD_PATH: 
DATA:
  DATASET: spacenet6optical
  TRAIN_DIR: '/home/yh.sakong/data/preprocessed/optical/train'
  VAL_DIR: '/home/yh.sakong/data/preprocessed/optical/val'
  TRAIN_BATCH: 2
  VAL_BATCH: 1
  NUM_WORKERS: 0
INTERVAL:
  MAX_INTERVAL: 80000
  VAL_INTERVAL: 2000
  LOG_INTERVAL: 100
CHECKPOINT:
  METRICS: ['Dice', 'IoU'] # ex) Dice, IoU
  BEST_METRIC: Dice # IoU Dice
  THRESHOLD: 0.3
OPTIM:
  LR: 2.e-05
  WEIGHT_DECAY: 0.05
  PARAMWISE:
    NUM_LAYERS: 24
    LAYER_DECAY_RATE: 0.9

  