EXP:
  EXP_NAME: test
  SAVE_DIR: # default : exp/{EXP_NAME}
MODEL:
  MODEL_NAME: UNet
  NETWORK_NAME: UNet
  IN_CHANNELS: 4
  NUM_CLASSES: 2
  PRETRAINED_PATH:
  LOAD_PATH: 
  IS_RESUME: False
DATA:
  DATASET: spacenet6sar
  TRAIN_DIR: '/home/yh.sakong/data/sn6_building/preprocessed/sar/train'
  VAL_DIR: '/home/yh.sakong/data/sn6_building/preprocessed/sar/val'
  TRAIN_BATCH: 8
  VAL_BATCH: 16
  NUM_WORKERS: 0
INTERVAL:
  MAX_INTERVAL: 80000
  VAL_INTERVAL: 100
  LOG_INTERVAL: 1
CHECKPOINT:
  METRICS: ['mDice'] # ex) Dice, IoU
  BEST_METRIC: mDice # IoU Dice
  THRESHOLD: 0.3
OPTIM:
  LR: 2.e-03
  WEIGHT_DECAY: 1.e-3
  