EXP:
  EXP_NAME: test
  SAVE_DIR: # default : exp/{EXP_NAME}
MODEL:
  MODEL_NAME: UNet
  NETWORK_NAME: UNet
  IN_CHANNELS: 4
  NUM_CLASSES: 1
  PRETRAINED_PATH: '/home/yh.sakong/github/Satellite/pretrained/beit_large_patch16_224_pt22k_ft22k_4channels.pth'
  RESUME_PATH:  
  LOAD_PATH: 
DATA:
  DATASET: spacenet6optical
  TRAIN_DIR: '/home/yh.sakong/data/sn6_building/preprocessed/optical/train'
  VAL_DIR: '/home/yh.sakong/data/sn6_building/preprocessed/optical/val'
  TRAIN_BATCH: 2
  VAL_BATCH: 32
  NUM_WORKERS: 0
INTERVAL:
  MAX_INTERVAL: 80000
  VAL_INTERVAL: 20
  LOG_INTERVAL: 1
CHECKPOINT:
  METRICS: ['Dice', 'IoU'] # ex) Dice, IoU
  BEST_METRIC: Dice # IoU Dice
  THRESHOLD: 0.3
OPTIM:
  LR: 2.e-03
  WEIGHT_DECAY: 1.e-3
  